
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:todly/core/routes/route_names.dart';
import 'package:todly/ui/view/create/create.dart';
import 'package:todly/ui/view/homepage/home.dart';
import 'package:todly/ui/view/lists/lists.dart';
import 'package:todly/ui/view/login/login.dart';
import 'package:todly/ui/view/onboarding/onboarding.dart';
import 'package:todly/ui/view/signup/signup.dart';
import 'package:todly/ui/view/singlelist/singlelist.dart';
import 'package:todly/ui/view/singlelist/singlelist_personal.dart';
import 'package:todly/ui/view/singlelist/singlelist_work.dart';
import 'package:todly/ui/view/splashscreen/splashscreen.dart';

class RouteGenerator {
  ///Routes are generated by this function
  static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {

      ///All views are registered here with appropriate page transition in this format
      case RouteNames.splashScreen:
        return CupertinoPageRoute(builder: (context) => SplashScreen());
        case RouteNames.onboarding:
        return CupertinoPageRoute(builder: (context) => Onboarding());
        case RouteNames.login:
        return CupertinoPageRoute(builder: (context) => LoginScreen());
        case RouteNames.signup:
        return CupertinoPageRoute(builder: (context) => SignUpScreen());
        case RouteNames.home:
        return CupertinoPageRoute(builder: (context) => HomeScreen());
        case RouteNames.create:
        return CupertinoPageRoute(builder: (context) => CreateScreen());
        case RouteNames.single:
        return CupertinoPageRoute(builder: (context) => SingleList());
        case RouteNames.list:
        return CupertinoPageRoute(builder: (context) => ListScreen());
        case RouteNames.single_work:
        return CupertinoPageRoute(builder: (context) => SingleListWork());
        case RouteNames.single_pers:
        return CupertinoPageRoute(builder: (context) => SingleListPers());
        break;
      
      default:
        return _errorRoute();
    }
  }

  ///Custom error route to ease debugging of unregistered routes
  static Route<dynamic> _errorRoute() {
    return CupertinoPageRoute(
      builder: (context) => Scaffold(
          appBar: AppBar(
              title: Text(
            'Page not found',
            style: TextStyle(color: Colors.red),
          )),
          body: Center(
            child: Text(
              'Error! Page not found',
              style: TextStyle(color: Colors.red),
            ),
          )),
    );
  }
}
